<a href="https://colab.research.google.com/github/Rakin7/Pytorch/blob/main/Pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

In [ ]:
!pip list

Package                          Version
-------------------------------- ---------------------
absl-py                          1.4.0
accelerate                       0.33.0
aiohappyeyeballs                 2.4.0
aiohttp                          3.10.5
aiosignal                        1.3.1
alabaster                        0.7.16
albucore                         0.0.14
albumentations                   1.4.14
altair                           4.2.2
annotated-types                  0.7.0
anyio                            3.7.1
argon2-cffi                      23.1.0
argon2-cffi-bindings             21.2.0
array_record                     0.5.1
arviz                            0.18.0
asn1crypto                       1.5.1
astropy                          6.1.3
astropy-iers-data                0.2024.8.27.10.28.29
astunparse                       1.6.3
async-timeout                    4.0.3
atpublic                         4.1.0
attrs                            24.2.0
audioread             

In [ ]:
import torch
import numpy as np
my_list=[[1,2,3,4],[5,6,7,8]]
print(my_list)

np1=np.random.rand(3,4)
print(np1)
np1.dtype

tensor_2d=torch.randn(3,4)
tensor_2d

tensor_3d=torch.zeros(2,3,4)
tensor_3d

[[1, 2, 3, 4], [5, 6, 7, 8]]
[[0.53786672 0.73981095 0.66466802 0.94509137]
 [0.35143336 0.96757438 0.88256663 0.8969472 ]
 [0.02194703 0.22254126 0.88702945 0.60209712]]


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [ ]:
my_tensor=torch.tensor(np1)
my_tensor

tensor([[0.5379, 0.7398, 0.6647, 0.9451],
        [0.3514, 0.9676, 0.8826, 0.8969],
        [0.0219, 0.2225, 0.8870, 0.6021]], dtype=torch.float64)

In [1]:
import torch
import numpy as np
my_list=[[1,2,3,4],[5,6,7,8]]
print(my_list)

np1=np.random.rand(3,4)
print(np1)
np1.dtype

tensor_2d=torch.randn(3,4)
tensor_2d

tensor_3d=torch.zeros(2,3,4)
tensor_3d
tensor_3d.dtype

[[1, 2, 3, 4], [5, 6, 7, 8]]
[[0.98919377 0.38666629 0.25873528 0.77065011]
 [0.57398838 0.00231142 0.09250124 0.6852248 ]
 [0.88389331 0.11459095 0.3697948  0.65599096]]


torch.float32

In [2]:
my_tensor=torch.tensor(np1)
my_tensor

tensor([[0.9892, 0.3867, 0.2587, 0.7707],
        [0.5740, 0.0023, 0.0925, 0.6852],
        [0.8839, 0.1146, 0.3698, 0.6560]], dtype=torch.float64)

In [4]:
mytorch=torch.arange(10)
mytorch
my_torch=mytorch.reshape(2,5)
my_torch
my_torch2=mytorch.reshape(2,-1)#if we do not know the size
my_torch2
mytorch3=torch.arange(15)
mytorch3
mytorch4=mytorch3.view(3,5)
mytorch4
mytorch7=torch.arange(10)
mytorch7
mytorch7[7]
mytorch8=mytorch7.reshape(5,2)
mytorch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

Neural Network

In [10]:
import torch
import torch.nn as nn
import torch.nn.functional as f
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

#Create a Model Class
class Model(nn.Module):

  # Input layer = 4 feature
  # two hidden layers
  #Output layer = 3
  def __init__(self, in_features=4, h1=8, h2=9, out_feature=3):
    super().__init__() #instantiate our nn.Module
    self.fc1=nn.Linear(in_features,h1) #fully connected
    self.fc2=nn.Linear(h1,h2) #fully connected
    self.out=nn.Linear(h2,out_feature) #output layer

  #move everything forward
  def forward(self,x):
    x = f.relu(self.fc1(x)) #rectify linear unit function
    x = f.relu(self.fc2(x))
    x = self.out(x)
    return x

In [9]:
#Pick a random seed for randomization
torch.manual_seed(41)
#Create an instance of model
model = Model()

In [13]:
#Loading data and changing column
url = 'https://gist.githubusercontent.com/netj/8836201/raw/6f9306ad21398ea43cba4f7d537619d0e07d5ae3/iris.csv'
my_df = pd.read_csv(url)
my_df['variety']=my_df['variety'].replace('Setosa', 0.0)
my_df['variety']=my_df['variety'].replace('Versicolor', 1.0)
my_df['variety']=my_df['variety'].replace('Virginica', 2.0)

<ipython-input-13-3dabf389fa20>:5: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  my_df['variety']=my_df['variety'].replace('Virginica', 2.0)


sepal.length  sepal.width  petal.length  petal.width  variety
0             5.1          3.5           1.4          0.2      0.0
1             4.9          3.0           1.4          0.2      0.0
2             4.7          3.2           1.3          0.2      0.0
3             4.6          3.1           1.5          0.2      0.0
4             5.0          3.6           1.4          0.2      0.0
..            ...          ...           ...          ...      ...
145           6.7          3.0           5.2          2.3      2.0
146           6.3          2.5           5.0          1.9      2.0
147           6.5          3.0           5.2          2.0      2.0
148           6.2          3.4           5.4          2.3      2.0
149           5.9          3.0           5.1          1.8      2.0

[150 rows x 5 columns]

In [15]:
# Train and Test
X = my_df.drop('variety', axis=1)
y = my_df['variety']
#Convert to numpy array
X = X.values
y = y.values

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])